version: 2
jobs:
  build:
    docker:
      - image: rust:1.44.1-buster
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cargo build
      - run:
          name: Test
          command: |
            cargo test

workflows:
  version: 2
  highlight:
    jobs:
      - build
