#!/usr/bin/env python3

import sys

def decode(s):
    """
    >>> decode('00')
    'nil'
    >>> decode('010')
    '0'
    >>> decode('01100001')
    '1'
    >>> decode('10100001')
    '-1'
    >>> decode('0111000010000')
    '16'
    """
    b01 = s[0:2]
    if b01 == '00':
        return 'nil'
    if b01 == '01' or b01 == '10':
        sign = +1 if b01 == '01' else -1
        index = s[2:].index('0')
        if index == 0:
            return '0'
        return str(sign * int(s[2+index+1:2+index+1+index*4], 2))
    return s # FAIL


if __name__ == "__main__":
    import doctest
    doctest.testmod()

    for line in sys.stdin:
        print(decode(line.strip()))
