#!/usr/bin/env python3

import sys

def main():
    s = sys.stdin.readlines()
    for i in range(len(s)):
        line = s[i]
        if line[len(line)-1] == '\n':
            line = line[:len(line)-1]
        s[i] = line

    w = len(s[0]) - 1
    h = len(s) - 1
    sum = 0
    d = 1
    for y in range(1, h+1):
        if s[y][0] != '#':
            raise RuntimeError("行が # で始まっていません")
        for x in range(1, w+1):
            if s[y][x] == '#':
                sum += d
            d *= 2
    if w != h:
        sum = -sum
    print(sum)

main()
